version: '3.8'

services:

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    networks:
      - app_net

  blue:
    build: .
    environment:
      - APP_VERSION=${APP_VERSION}
      - HEALTH_MODE=${HEALTH_MODE}
    networks:
      - app_net

  green:
    build: .
    environment:
      - APP_VERSION=${APP_VERSION}
      - HEALTH_MODE=${HEALTH_MODE}
    networks:
      - app_net

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx:/etc/nginx   # 🔥 FIX CLAVE
    depends_on:
      - blue
      - green
    networks:
      - app_net

networks:
  app_net:

volumes:
  jenkins_home: